//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use sea_orm::{Set, NotSet};
use serde::{Deserialize, Serialize};

// 为新架构添加的转换imports
use crate::domain::article::aggregate::Article;
use crate::domain::article::value_objects::{Content, Id, Slug, Status, Summary, Title};
use crate::shared::errors::RhyonError;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "articles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    pub title: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub published_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

// 转换实现：从聚合根到数据库实体
impl From<Article> for ActiveModel {
    fn from(article: Article) -> Self {
        ActiveModel {
            id: match article.id() {
                Some(id) => Set(*id.value()),
                None => NotSet,
            },
            title: Set(article.title().value().to_string()),
            slug: Set(article.slug().value().to_string()),
            summary: Set(article.summary().value().to_string()),
            content: Set(article.content().value().to_string()),
            status: Set(article.status().as_str().to_string()),
            created_at: Set(article.created_at().clone().into()),
            updated_at: Set(article.updated_at().clone().into()),
            published_at: Set(article.published_at().map(|dt| dt.clone().into())),
        }
    }
}

// 转换实现：从数据库模型到聚合根
impl TryFrom<Model> for Article {
    type Error = RhyonError;

    fn try_from(model: Model) -> Result<Self, Self::Error> {
        let title = Title::new(model.title)?;
        let slug = Slug::new(model.slug)?;
        let summary = Summary::new(model.summary)?;
        let content = Content::new(model.content);
        let status = Status::from_str(&model.status)?;
        
        Ok(Article::reconstitute(
            Some(Id::from(model.id)),
            slug,
            title,
            summary,
            content,
            status,
            model.created_at.into(),
            model.updated_at.into(),
            model.published_at.map(|dt| dt.into()),
        ))
    }
}

// 为了向后兼容，保留原有的From实现
impl From<Model> for Result<Article, RhyonError> {
    fn from(model: Model) -> Self {
        model.try_into()
    }
}
